# Generated by Django 3.1 on 2022-11-04 05:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тема домашнего задания')),
                ('postDate', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публикации')),
                ('content', tinymce.models.HTMLField(verbose_name='Описание выполнения работы')),
            ],
            options={
                'verbose_name': 'Домашняя работа',
                'verbose_name_plural': 'Домашние задания',
                'db_table': 'homeworks',
            },
        ),
        migrations.CreateModel(
            name='LessonLecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тема урока')),
                ('postDate', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публикации')),
                ('content', tinymce.models.HTMLField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Лекция',
                'verbose_name_plural': 'Лекции',
                'db_table': 'lessons',
            },
        ),
        migrations.CreateModel(
            name='VideoMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessonName', models.CharField(max_length=255, verbose_name='Тема урока')),
                ('postDate', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публикации')),
                ('video', models.FileField(upload_to='materials/video/', verbose_name='Видео файл (mp4)')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео материалы',
                'db_table': 'videomaterials',
            },
        ),
        migrations.CreateModel(
            name='FeedbackHomeWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeWork', models.FileField(upload_to='materials/homeWorks/', verbose_name='Файл (pdf)')),
                ('student', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Домашняя работа',
                'verbose_name_plural': 'Домашние задания',
                'db_table': 'feedbacks',
            },
        ),
    ]
