# Generated by Django 4.1.3 on 2022-11-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformApp', '0002_aboutpage_mainpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentaion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessonTheme', models.CharField(max_length=255, verbose_name='Тема урока')),
                ('presentationUrl', models.CharField(max_length=500, verbose_name='Ссылка презентации')),
            ],
            options={
                'verbose_name': 'Презентация',
                'verbose_name_plural': 'Презентации',
                'db_table': 'presentations',
            },
        ),
        migrations.AlterModelOptions(
            name='feedbackhomework',
            options={'verbose_name': 'Отправленное ДЗ', 'verbose_name_plural': 'Отправленные ДЗ'},
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='feedbackhomework',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lessonlecture',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='videomaterial',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
