# Generated by Django 4.1.3 on 2022-11-08 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platformApp', '0003_presentaion_alter_feedbackhomework_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedbackHomeWork',
        ),
    ]
