# Generated by Django 4.1.3 on 2022-11-08 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('platformApp', '0004_delete_feedbackhomework'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeHomework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(max_length=255, verbose_name='Оценка')),
                ('homeWork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platformApp.homework', verbose_name='Задание #')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ученик/ца')),
            ],
            options={
                'verbose_name': 'Выполненная работа',
                'verbose_name_plural': 'Выполненные работы',
            },
        ),
    ]
