# Generated by Django 4.1.3 on 2022-11-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformApp', '0007_pushhomework_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushhomework',
            name='solution',
            field=models.FileField(upload_to='materials/homeWorks/', verbose_name='Файл'),
        ),
        migrations.AlterModelTable(
            name='pushhomework',
            table='ppvideomaterials',
        ),
    ]
