# Generated by Django 4.1.3 on 2022-11-08 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('platformApp', '0008_alter_pushhomework_solution_alter_pushhomework_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushhomework',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ученик/ца'),
        ),
    ]
