# Generated by Django 4.1.3 on 2022-11-08 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platformApp', '0009_alter_pushhomework_student'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pushhomework',
            table=None,
        ),
    ]
