# Generated by Django 4.1.3 on 2022-11-08 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformApp', '0010_alter_pushhomework_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradehomework',
            name='postDate',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время'),
        ),
    ]
