# Generated by Django 4.1.3 on 2023-05-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformApp', '0011_gradehomework_postdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='FourthBlock',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='4-блок'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='firstBlock',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='1-блок'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='secondBlock',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='2-блок'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='thirdBlock',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='3-блок'),
        ),
    ]
