# Generated by Django 4.1.3 on 2023-05-14 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platformApp', '0012_mainpage_fourthblock_mainpage_firstblock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainpage',
            old_name='FourthBlock',
            new_name='fourthBlock',
        ),
    ]
